@startuml Player

title Player Class Diagram

class Player

class PlayerMovement {
    == Data ==
    .. Public Data ..
    +float gravity
    .. Private Data ..
    -PlayerData PD
    -AnimationPlayer Anime
    -Vector2 RollVelocity
    == Methods ==
    .. Public Methods ..
    +_Ready() : void
    +_PhysicsProcess() : void 
    +ApplyGravity() : float {float velocity, float timeDelta}
    +HandleJump() : float {float velocity, float jumpVelocity}
    +LateralMovements() : Vector2 {Vector2 velocity, float delta}
    +PlayerDodgeRoll() : Vector2 {Vector2 velocity, float delta}
    +GetGlobalInputDirection() : Vector3
    .. Private Methods ..
}

Player *-down- PlayerMovement

@enduml