@startuml Player Object

title Player Object Diagram

object Player

object Mesh
object Collider
object Head
object Inventory
object "Player Data" as PlayerData
object Anime
object "1st Person Camera" as FPS
object "3rd Person Camera" as TPS
object "Player UI" as PlayerUI
object "Inventory UI" as InventoryUI
object "Item Pickup Area" as ItemPickupArea
object "Equipped Item Slot" as EquipItemSlot
object "Item Pickup Shape" as ItemPickupShape
object "Primary Attack" as PrimaryAttack

Player : Type = CharacterBody3D
Mesh : Type = MeshInstance3D
Collider : Type = ColliderShape3D
Head : Type = Node3D
Inventory : Type = Node3D
PlayerData : Type = Node3D
Anime : Type = AnimationPlayer
FPS : Type = Camera3D
TPS : Type = Camera3D
PlayerUI : Type = CanvasLayer
InventoryUI : Type = Control
ItemPickupArea : Type = Area3D
EquipItemSlot : Type = Node3D
ItemPickupShape : Type = ColliderShape3D
PrimaryAttack : Type = Node3D

Player *-- Mesh
Player *-- Collider
Player *-- Head
Player *-- Inventory
Player *-- PlayerData
Player *-- Anime

Head *-- FPS
Head *-- TPS

FPS *-- PlayerUI
FPS *-- InventoryUI

Inventory *-- ItemPickupArea
Inventory *-- EquipItemSlot

ItemPickupArea *-- ItemPickupShape

EquipItemSlot *-- PrimaryAttack

@enduml