@startuml Player Class

title Player Class Diagram

class PlayerDataDecorator <<Player Data>>{
    == Data == 
    .. Private ..
    - PlayerData PD
    .. Public ..
    == Methods ==
    .. Private ..
    .. Public ..
    + Get..()
    + Set..()
}

class PlayerMovement <<Player Movement>>{
    == Data ==
    .. Public Data ..
    +float gravity
    .. Private Data ..
    -AnimationPlayer Anime
    -Vector2 RollVelocity
    == Methods ==
    .. Public Methods ..
    +_Ready() : void
    +_PhysicsProcess() : void 
    +ApplyGravity() : float
    +HandleJump() : float
    +LateralMovements() : Vector2
    +PlayerDodgeRoll() : Vector2
    +GetGlobalInputDirection() : Vector3
    .. Private Methods ..
}

class CameraMovement <<Head>>{
    == Data ==
    .. Public ..
    +Camera3D FP
    +Camera3D TP
    +Camera3D ActiveCamera
    .. Private ..
    == Methods ==
    .. Public ..
    +_Ready() : void
    +_Process() : void
    +_UnhandledInput() : void
    +MouseCameraMovement() : void
    +SwitchCamera() : void
    .. Private ..
    +SetActiveCamera() : void
}

class InventoryManager <<Inventory>>{
    == Data ==
    .. Public ..
    +float maxInventoryWeight
    +float currInventoryWeight
    .. Private ..
    -ItemPickupZone ItemPickupArea
    -EquippedItem EquippedItemSlot
    -PlayerUI PlayerUI
    -InventoryUI InventoryUI
    -List MainInventory : Item
    -ulong[,] InventoryGrid
    == Methods ==
    .. Public ..
    +_Ready() : void
    +_Input() : void
    +PickupItem(): void 
    +EquipItem(): void
    +CheckCurrInventoryWeight(): void
    +AddItemToInvGrid(): bool
    +SumInventoryRegion(): ulong
    +UpdateInventoryRegion(): void
    .. Private ..
}

class PlayerAnimationDirector <<Anime>> {
    == Data ==
    .. Private ..
    .. Public ..
    == Methods ==
    .. Private ..
    .. Public ..
    + PlayRollAnimation() : void
    + CheckPlayingStatus() : bool
    + GetCurrentAnimationName() : bool
}

PlayerDataDecorator *-- PlayerMovement
PlayerDataDecorator *-- CameraMovement
PlayerDataDecorator *-- InventoryManager
PlayerMovement *-- PlayerAnimationDirector

@enduml